### ISSUE TITLE
Problem downloading genomes

### ISSUE THREAD

**Issue by dbsseven** [HajkD/biomartr#7] opened 2017-03-14 23:25 UTC
Hello,
I am new to R and biomartr but am having a bit of trouble downloading genomes from ensembl. The example case of Arabidopsis thaliana works fine but trying Escherichia coli or Bacillus cereus give an error with curl. The is.genome.available query returns true however. The error I'm getting isn't descriptive enough for me to sort it out. Below is the code I'm running in the console and the errors I'm getting. Any help would be much appreciated.

> biomartr::getGenome(db  = "ensemblgenomes", organism ="Escherichia coli",path= file.path("_ncbi_downloads","genomes"))
Error in curl::curl(url = url, "rb", curl::new_handle(dirlistonly = TRUE)) : 
  Access denied to remote resource
> biomartr::getGenome(db  = "ensemblgenomes", organism ="Bacillus cereus",path= file.path("_ncbi_downloads","genomes"))
Error in curl::curl(url = url, "rb", curl::new_handle(dirlistonly = TRUE)) : 
  Access denied to remote resource

**Comment by HajkD** [comment] 2017-03-15 12:01
Hi @dbsseven 

Thank you so much for making me aware of this problem! 

I could reproduce the error and I will try to figure out why ENSEMBLGENOMES allows the access for some species (e.g. A. thaliana) but not for others.  

I will try to fix the problem and will come back to you asap.

Many thanks and best wishes,
Hajk

**Comment by HajkD** [comment] 2017-03-15 12:07
PS: The retrieval from NCBI Genbank works seamlessly

>biomartr::getGenome(db = "genbank", organism ="Bacillus cereus",path= file.path("_ncbi_downloads","genomes"))

and

>biomartr::getGenome(db = "genbank", organism ="Escherichia coli",path= file.path("_ncbi_downloads","genomes"))

So it seems to be an ENSEMBLGENOMES specific issue.

I am on it :)

Cheers,
Hajk

**Comment by dbsseven** [comment] 2017-03-15 13:45
Thank you for looking into this and good to know the NCBI Genbank version works. I'll have to give that a try and see if it it works for my purpose.

**Comment by HajkD** [comment] 2017-03-22 12:42
Hi @dbsseven,

I finally found the problem!

The problem was that ENSEMBLGENOMES stores bacteria genomes in so-called "collections" (see  ftp://ftp.ensemblgenomes.org/pub/current/bacteria/fasta/). All other taxonomic division do not have this collection structure. When I implemented the new function `exists.ftp.file()` to check whether a specified ftp file is availability or not, I did not consider this collection structure as special case for bacteria.

I now fixed this issue and now the following commands work properly (https://github.com/HajkD/biomartr/commit/a0f6a04615644b6203dce83e4e481302379611d0):

>biomartr::getGenome(db = "ensemblgenomes", organism ="Escherichia coli",path= file.path("_ncbi_downloads","genomes"))

> biomartr::getGenome(db = "ensemblgenomes", organism ="Bacillus cereus",path= file.path("_ncbi_downloads","genomes"))

The error:

>Error in curl::curl(url = url, "rb", curl::new_handle(dirlistonly = TRUE)) :
Access denied to remote resource

occurred, because internally the `exists.ftp.file()` tried to access an invalid ftp path on the ENSEMBLGENOMES server.

Thank you so much again for pointing this bug out to me. I hope that everything works properly now :)

Best wishes,
Hajk

**Closed** 2017-03-22 15:15 UTC
Labels: bug
